start:
	npx webpack

start-prod:
	echo 'implement me'

build:
	NODE_ENV=production npx webpack

analyze-bundle:
	NODE_ENV=production ANALYZE=true npx webpack

lint:
	npx eslint .
	npx tsc

prettier:
	npx prettier --write .
